---

- hosts: all
  become: true
  gather_facts: no
  tasks: 

    - name: Remove httpd package
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: absent
        autoremove: true
