---

- hosts: all
  become: true
  gather_facts: no
  tasks: 

  - name: Stop the httpd service
    ansible.builtin.service:
            name: httpd
            state: stopped
            enabled: false
    ignore_errors: true       
