---

- hosts: all
  become: true
  gather_facts: no
  tasks: 

  - name: Stop the httpd service
    service:
            name: "{{ apache_package }}"
            state: stopped
            enabled: false
    ignore_errors: true       

  - name: Stop the php-fpm service
    service:
            name: "{{ php_package }}"
            state: stopped
            enabled: false
    ignore_errors: true
